name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests and check coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies directly
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests and enforce coverage threshold
        run: |
          PYTHONPATH=src pytest --cov=src src/tests --cov-fail-under=80
